### ISSUE TITLE
[Question] Use a real HDD?

### ISSUE THREAD

**Issue by Dokman** [TheLastRar/CLR-DEV9#2]
So yes i have a 1TB HDD of ps2 games, formated in order to use it with the PS2, can be supported? so i don't have to make all the copies of my games again

**Comment by Dokman** [comment]
i am tired to make mi own copies of the ratchet and clank god of war and etc i have like 160 games with all the packages, and i am tired to make an iso of all the games again

**Comment by requeijaum** [comment]
Can't you create an image with GNU dd of your HDD and use it as a RAW file?

**Comment by Dokman** [comment]
@requeijaum i Will try to do it

**Comment by requeijaum** [comment]
Can @TheLastRar implement direct read and write to block devices or pipes in POSIX-compliant systems? I know that the PS2 HDD uses the PlayStation File System, from Sony's PS2 SDK. Maybe the free @ps2dev have an implementation for using SMB, host, or NFS.

**Comment by TheLastRar** [comment]
On Linux, using block devices works as they can be opened with the same apis as normal files, although the config screen won't take kindly to you trying it.

Edit: If you use a real HDD as the block device, make a backup before using this plugin on it.

The configure screen can't get the size of block devices so it assumes a size of 0, so you will need to edit the config file to the correct size (in Mib) and path. It may also try to add an extension instead, which you can just remove in the input field.

You may need to run PCSX2 with sudo as you may get an access denied error message otherwise.

Regarding pipes, I'm not aware of pipes being seek-able, so there would need some other way to inform the other side of the pipe where the read/write should be.

It may be possible to HLE the file system, much like folder memory cards and this plugin's winsock method does. This is probably a sizeable undertaking and would also end up covering a lot of the work needed for https://github.com/TheLastRar/CLR-DEV9/issues/1.
