### ISSUE TITLE
Notice: PCSX2 is merging plugins 

### ISSUE THREAD

**Issue by F0bes** [TheLastRar/CLR-DEV9#31]
Hello, I feel bad having to say this but there is an ongoing effort to merge each plugin into core. Due to the fact that CLR-DEV9 is written in a managed language, we are unable to merge it. 

I've mentioned doing some magic to load the library without the plugin interface but it wouldn't be feasible to have a system just for a singular plugin.

Version 1.6 (and maybe 1.7) will still have the original dev9 plugin system.

I tried to find you in the pcsx2 discord and couldn't find you. If you'd like to discuss this change with the main contributors you're welcome to join.

**Comment by TheLastRar** [comment]
Yes, the choice is managed language is because I'm more familiar with C# than C++
I would need a fair amount of help (and time) to get a C++ port up and running

I probably won't have enough time until after mid-october at least, but I'll see

I'm already in the PCSX2 discord, under the name AirGamer (Same avatar)

Also, is their a similar effort for the USB plugin? while mine is not as unique as the others that float around, it does have some fixes that would need to be ported back into C++

**Comment by refractionpcsx2** [comment]
Hi @TheLastRar thanks for responding to us, it would be great to get your clr-dev9 plugin merged instead of dev9drkghz as your plugin is generally superior, so if we can port it to C++ that would be super, the ethernet side of it might be a slight pain though, one of the other contributors has already been working on converting the other plugin and changed the interface to use TAP, which you may also need to use for windows unless somehow there's a cunning way we can link to .net libraries from C++...

As for USB, yes we are hoping to get Jackun's usb-wheel plugin integrated due to its support for every USB device, that's going to need some work too.

**Comment by TheLastRar** [comment]
Yeah, networking would be a pain point, as not only would I lose the multiplatform networking api, but I'm also using somewhat high level apis within that in a fair number of places.

Mono and CoreCLR are the go to for multiplatform loading of .net libaries.

I did notice the PR regarding the revisions to dev9drkghz, I need to compare what he has done with respect to how I handle TAP in my plugin

As for USB, be sure to test https://github.com/PCSX2/pcsx2/issues/310, which my USB plugin currently works around. I dunno if Jackun has dealt with that same issue by now.

I havn't used Jackun's usb-wheel recently, last time I used it keyboard support was only in some random test verion burried in the fourms, It seems like that is now a mainline feature.

**Comment by refractionpcsx2** [comment]
As far as I'm aware @jackun 's plugin seems to work, not sure if it's an issue, but tagged him here anyway, so he can double check

**Comment by jackun** [comment]
I think there's some kind of a workaround. If it gets weird read/write address it just resets the whole ohci.

**Comment by vico93** [comment]
I'm upset PCSX2 team decided to use the only plugin which doesn't work in my system (even having Win10pcap installed), removing the option to choose other plugin which works, in case CLR-DEV9.
